# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matt Roberts
email: mail@mattroberts.eu
description: > # this means to ignore newlines until "baseurl:"
  Notes on scala, python, bash, git, aws and more
permalink: /:year/:month/:day/:title/
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mattroberts.eu" # the base hostname & protocol for your site
twitter_username: mattroberts297
github_username:  mattroberts297

# Build settings
markdown: kramdown

kramdown:
  input: GFM
